### ISSUE TITLE
Persistent State Between Windows

### ISSUE THREAD

**Issue by jspaniac** [pandabear15/equidistant#20]
Currently the frontend approach of using navigate w/ state allows us to pass information between pages, however it doesn't allow the state to persist once we've navigated to another window. For example:

1. Login to the application
2. Navigate to the account page
3. Click the back button

We'd have to pass relevant information for the landing page that isn't relevant for the account page (like friends, friend requests) just so we could pass it back on the back button. Should probably investigate a different solution to passing state (maybe window.localStorage?)

**Comment by zshafe** [comment]
I'm looking into this too! Feels like something we should solve before moving too much further in terms of our functionality

**Comment by zshafe** [comment]
fixed in #24
