### ISSUE TITLE
[BUG] Sign up

### ISSUE THREAD

**Issue by tommydgithub** [pandabear15/equidistant#54]
**Describe the bug**
The sign up doesn't work

**To Reproduce**
username
tdelar@uw.edu
password
testtest
address
4733 17th Ave NE, Seattle, WA 98105

**Expected behavior**
I would get taken to a different page or those credentials would work to sign in

**Screenshots**

**User information**
- Device Type mac book
 - OS: [e.g. iOS] macOS monteray
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 110 chrome version

**Additional context**

**Comment by jspaniac** [comment]
Resolved in #64
