### ISSUE TITLE
[BUG] <Sign up issue>

### ISSUE THREAD

**Issue by riteshsb** [pandabear15/equidistant#55]
**Describe the bug**
Created user credentials but was not able to get past the sign in with a new account. 

**To Reproduce**
Clicked on link. Clicked on "Don't have an account? sign up". Entered credentials in Email Address and Password to set. Clicked create account. 

**Expected behavior**
I expected the page to move past the create account page and either back to the sign in page or into the Equidistant main page. I tried clicking on "Already have an account. Login". This worked and went back to the sign in page saved my created credentials but it was not able to proceed further. 

**Screenshots**

**User information**
- Device Type
 - OS: macOS
 - Browser Chrome
 - Version 110.0.5481.100 (Official Build) (x86_64)

**Additional context**
I understand this part of the issue may not have been developed yet. When it is working you may want to keep in mind that the user would like to directly go to the main page after creating an account and not have to see the sign in page again. Additionally, may want to include measures for if password was taken or ineligible.

**Comment by jspaniac** [comment]
Resolved in #64
